

server:
  port: 9010
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb 

    driver-class-name: com.mysql.cj.jdbc.Driver
    
    username: root
    
    password: data
    
  jpa:
    hibernate:
      ddl-auto: update